config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  get "users/show" => "users#show"
  get "charts" => "charts#index"
  root to: 'home#index'
  resources :budgetbooks
  resources :progresses
  resources :posts do
    collection do
      get :mypost
    end
  end
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/shared/_partial.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to '家計簿', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to '家計簿', budgetbooks_path, class: "btn btn-secondary m-1" %>
        </li>
        <li class="nav-item">
          <%= link_to "グラフ", charts_path, class: "btn btn-secondary m-1" %>
        </li>
        <li class="nav-item">
          <%= link_to '目標貯金額', progresses_path, class: "btn btn-secondary m-1" %>
        </li>
        <li class="nav-item">
          <%= link_to '節約のコツ', posts_path, class: "btn btn-secondary m-1" %>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "アカウント設定", users_show_path, class: 'btn btn-primary m-1' %>
          </li>
          <li class="nav-item">
            <%= link_to 'ログアウト', destroy_user_session_path, data: { turbo_method: :delete }, class: 'btn btn-danger m-1' %>
          </li>
          <li class="nav-item">
            <span class="nav-link active mt-1 mb-1">ようこそ<%= @user.name %> さん</span>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "ログイン", new_user_session_path, class: 'btn btn-primary m-1' %>
          </li>
          <li class="nav-item">
            <%= link_to "新規登録", new_user_registration_path, class: 'btn btn-danger m-1' %>
          </li>
          <li class="nav-item">
            <%= link_to "ゲストログイン", users_guest_sign_in_path, data: { "turbo-method": :post }, class: 'btn btn-success m-1' %>
          </li>
        <% end %>     
      </ul>
    </div>
  </div>
</nav>